### ISSUE TITLE
Implement `verify` command

### ISSUE THREAD

**Issue by tetsuo-cpp** [trailofbits/sigstore-python#10]

**Comment by jku** [comment]
This is really interesting work you've done. I have a related issue in securesystemslib (TUF crypto component) where I've outlined what securesystemslib could do WRT fulcio verification MVP: 
https://github.com/secure-systems-lab/securesystemslib/issues/399

I'm interested in these questions:
* are the checks in my rough example reasonable / complete enough?
* is there a way to verify certificate chain validity with cryptography only? I did not find one
* my hunch is that Securesystemslib should implement verify independently (to avoid dependency for the verifying client) but use sigstore-python for the signing: does this sound reasonable?
* I understand sigstore-python might want to implement the rekor lookup in verify (to make sure the cert was actually valid at signing time): I think that should be optional though, and especially in TUF case it's not as critical... would be interested in opinions about this

Don't feel like I'm demanding answers: I'm mostly writing this down for future and assume I'll get my answers when this issue gets a PR :)

**Comment by di** [comment]
👋 Hi @jku!

> are the checks in my rough example reasonable / complete enough?

I think these will be very helpful to include as we finish implementing the Fulcio client (see #15).

> is there a way to verify certificate chain validity with cryptography only (and without using pyopenssl)? I did not find one

Unfortunately no: https://github.com/pyca/cryptography/issues/2381

> my hunch is that Securesystemslib should implement verify independently (to avoid dependency for the verifying client) but use sigstore-python for the signing: does this sound reasonable?

Entirely up to you! What's the main reason you want to avoid the dependency for the verifying client?

> I understand sigstore-python might want to implement the rekor lookup in verify (to make sure the cert was actually valid at signing time): I think that should be optional though, and especially in TUF case it's not as critical... would be interested in opinions about this

Yep, I think we'll want to support 'offline' verification here if possible as well.

**Comment by jku** [comment]
> What's the main reason you want to avoid the dependency for the verifying client?

Oh just the knee jerk reaction from trying to keep python-tuf dependencies to an absolute minimum so that it's acceptable to potential pip vendoring.

Obviously in this specific case cryptography and pyopenssl are the elephants in the room:  I have no idea if implementing this without a dependency, especially a C dependency, is realistic at all but... just in case there is a chance to do that (after the concept has been first proven with an easy cryptography implementation), I'd rather keep dependencies to a minimum in general.
